# Generated by Django 3.2 on 2022-02-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220203_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Product',
        ),
    ]
