# Generated by Django 4.0.2 on 2022-02-09 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projet',
            name='temp_allocated',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'le temps min doit etre 1 heure')]),
        ),
    ]
