# Generated by Django 3.2 on 2022-03-14 13:17

import django.core.validators
from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_projet_description_alter_projet_temp_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='temp_allocated',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'le temps min doit etre 1 heure'), django.core.validators.MaxValueValidator(10, 'le temps max doit etre 10 heure')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[hub.models.validate_email], verbose_name='Email'),
        ),
    ]
